[package]
authors = ["Frankie Bagnardi <f.bagnardi@gmail.com>"]
edition = "2018"
name = "glint"
version = "0.1.2"
description = "a friendly tool for creating commits in the commitlint style"
license = "MIT"

[dependencies]
clap = "2"
crossterm = "0.10"
unic-segment = "0.9"

[profile.release]
lto = true
debug = false
opt-level = 3
