name: Compile/Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
          
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
