name: Test/Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo test --verbose
    - name: Release build
      run:
        - cargo build --release
        - mkdir -p artifacts/glint-${{ matrix.os }}
        - cp target/release/glint artifacts/glint-${{ matrix.os }}
    - uses: actions/upload-artifact@master
      with:
        name: glint-${{ matrix.os }}
        path: artifacts/glint-${{ matrix.os }}

